run:
  timeout: 2m
linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - revive
    - gosimple
    - gofmt
    - goimports

gofmt:
  simplify: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
